import { useCallback, useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";

import {
  clearForemanDataset,
  getForemanDatasetStatus,
  loadForemanSampleDataset,
  runForemanAnalysis,
  uploadForemanDataset,
} from "../services/foremanAnalysisApi";
import "./ForemanAnalysis.css";

// Friendlier labels + order for the issue categories the backend returns,
// plus a one-line explanation so a reader doesn't have to guess what
// "Traceability" or "Hierarchy" means in this context.
const CATEGORY_INFO = {
  Capacity: {
    order: 0,
    blurb: "A sprint or team member is committed beyond their available capacity.",
  },
  Dependency: {
    order: 1,
    blurb: "Missing, invalid, circular, or out-of-order dependencies between items.",
  },
  Readiness: {
    order: 2,
    blurb: "Stories or tasks missing acceptance criteria or a Definition of Done.",
  },
  Hierarchy: {
    order: 3,
    blurb: "Items with no parent, or a parent that doesn't exist in the backlog.",
  },
  Traceability: {
    order: 4,
    blurb: "Epics that aren't linked back to a valid solution/architecture section.",
  },
  Estimation: {
    order: 5,
    blurb: "Stories or tasks with no valid story-point estimate.",
  },
};

const STAGE = {
  CHECKING: "checking", // asking the backend if a dataset is already loaded
  EMPTY: "empty", // no dataset loaded — show upload / sample options
  LOADING_DATASET: "loading_dataset", // uploading or loading the sample
  ANALYZING: "analyzing", // dataset loaded, running the analysis
  READY: "ready", // report is visible
  ERROR: "error",
};

function pct(confidence) {
  if (confidence == null) return "—";
  return `${Math.round(confidence * 100)}%`;
}

function Pill({ tone, children }) {
  return <span className={`fa-pill fa-pill-${tone}`}>{children}</span>;
}

// ===========================================================
// Empty state — the report is intentionally NOT preloaded.
// A dataset must be provided (upload or sample) before any
// analysis runs, so the person always knows what they're
// looking at and where it came from.
// ===========================================================
function DatasetGate({ onFileChosen, onUseSample, busy, errorMessage }) {
  const [isDragging, setIsDragging] = useState(false);
  const inputRef = useRef(null);

  const handleFiles = (fileList) => {
    const file = fileList && fileList[0];
    if (file) onFileChosen(file);
  };

  return (
    <div className="fa-page">
      <div className="fa-shell">
        <header className="fa-header">
          <div>
            <div className="fa-eyebrow">FOREMAN ANALYSIS</div>
            <h1>How healthy is this backlog?</h1>
            <p className="fa-subtitle">
              A plain-English read on readiness, dependencies, capacity, and
              the delivery forecast — generated by the Foreman engine, not by
              an LLM.
            </p>
          </div>
        </header>

        <section
          className={`fa-dropzone ${isDragging ? "fa-dropzone-active" : ""} ${
            busy ? "fa-dropzone-busy" : ""
          }`}
          onDragOver={(e) => {
            e.preventDefault();
            if (!busy) setIsDragging(true);
          }}
          onDragLeave={() => setIsDragging(false)}
          onDrop={(e) => {
            e.preventDefault();
            setIsDragging(false);
            if (!busy) handleFiles(e.dataTransfer.files);
          }}
        >
          <div className="fa-dropzone-icon">📊</div>

          {busy ? (
            <>
              <div className="fa-spinner" />
              <h2>Reading your data…</h2>
              <p className="fa-muted">This only takes a moment.</p>
            </>
          ) : (
            <>
              <h2>No dataset loaded yet</h2>
              <p className="fa-muted">
                You can upload one here, or go back and add it from the plan
                input screen — either way it's shared across the app, so you
                won't be asked twice.
              </p>

              <button
                type="button"
                className="fa-btn fa-btn-primary"
                onClick={() => inputRef.current?.click()}
              >
                Choose file…
              </button>

              <input
                ref={inputRef}
                type="file"
                accept=".xlsx,.xlsm"
                hidden
                onChange={(e) => handleFiles(e.target.files)}
              />

              <div className="fa-dropzone-divider">
                <span>or</span>
              </div>

              <button
                type="button"
                className="fa-link-btn fa-link-btn-center"
                onClick={onUseSample}
              >
                Try it with sample data instead
              </button>
            </>
          )}
        </section>

        {errorMessage && (
          <div className="fa-inline-error">
            <strong>Couldn't use that file.</strong> {errorMessage}
          </div>
        )}

        <p className="fa-fineprint">
          Expected sheets: <code>Backlog</code>, <code>Dependencies</code>,{" "}
          <code>Sprints</code>, <code>TeamMembers</code>, <code>Holidays</code>
          . Nothing is analyzed until you provide data — there's no
          preloaded report.
        </p>
      </div>
    </div>
  );
}

export default function ForemanAnalysis() {
  const navigate = useNavigate();

  const [stage, setStage] = useState(STAGE.CHECKING);
  const [report, setReport] = useState(null);
  const [datasetSource, setDatasetSource] = useState(null);
  const [error, setError] = useState("");
  const [openPanel, setOpenPanel] = useState(null); // "issues" | "plan"

  // Runs the analysis against whatever dataset is currently loaded on the
  // backend. Assumes the dataset is already loaded — callers are
  // responsible for that.
  const analyze = useCallback(async () => {
    setStage(STAGE.ANALYZING);
    setError("");
    try {
      const result = await runForemanAnalysis();
      setReport(result);
      setStage(STAGE.READY);
    } catch (err) {
      console.error("Foreman analysis failed:", err);
      setError(
        err.message ||
          "Could not reach the backend. Is it running on http://localhost:8000?",
      );
      setStage(STAGE.ERROR);
    }
  }, []);

  // On mount: only check whether a dataset already exists — never load one
  // automatically. This is what keeps the report from appearing before the
  // person has actually provided data.
  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const status = await getForemanDatasetStatus();
        if (cancelled) return;

        if (status.loaded) {
          setDatasetSource(status.source);
          analyze();
        } else {
          setStage(STAGE.EMPTY);
        }
      } catch (err) {
        console.error("Could not check dataset status:", err);
        if (!cancelled) {
          setError(
            err.message ||
              "Could not reach the backend. Is it running on http://localhost:8000?",
          );
          setStage(STAGE.ERROR);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [analyze]);

  const handleFileChosen = async (file) => {
    setStage(STAGE.LOADING_DATASET);
    setError("");
    try {
      const result = await uploadForemanDataset(file);
      setDatasetSource(result.source || file.name);
      await analyze();
    } catch (err) {
      console.error("Dataset upload failed:", err);
      setError(err.message || "Something went wrong reading that file.");
      setStage(STAGE.EMPTY);
    }
  };

  const handleUseSample = async () => {
    setStage(STAGE.LOADING_DATASET);
    setError("");
    try {
      const result = await loadForemanSampleDataset();
      setDatasetSource(result.source || "Sample dataset");
      await analyze();
    } catch (err) {
      console.error("Sample dataset load failed:", err);
      setError(err.message || "Could not load the sample dataset.");
      setStage(STAGE.EMPTY);
    }
  };

  const handleUseDifferentDataset = async () => {
    try {
      await clearForemanDataset();
    } catch (err) {
      console.error("Could not clear dataset:", err);
    }
    setReport(null);
    setDatasetSource(null);
    setOpenPanel(null);
    setStage(STAGE.EMPTY);
  };

  // ---------------------------------------------------------
  // Loading / gate states
  // ---------------------------------------------------------

  if (stage === STAGE.CHECKING) {
    return (
      <div className="fa-page">
        <div className="fa-card fa-center">
          <div className="fa-spinner" />
          <p>Checking for a loaded dataset…</p>
        </div>
      </div>
    );
  }

  if (stage === STAGE.EMPTY || stage === STAGE.LOADING_DATASET) {
    return (
      <DatasetGate
        onFileChosen={handleFileChosen}
        onUseSample={handleUseSample}
        busy={stage === STAGE.LOADING_DATASET}
        errorMessage={stage === STAGE.EMPTY ? error : ""}
      />
    );
  }

  if (stage === STAGE.ANALYZING) {
    return (
      <div className="fa-page">
        <div className="fa-card fa-center">
          <div className="fa-spinner" />
          <p>Running Foreman analysis…</p>
        </div>
      </div>
    );
  }

  if (stage === STAGE.ERROR) {
    return (
      <div className="fa-page">
        <div className="fa-card fa-center">
          <div className="fa-error-icon">⚠️</div>
          <h2>Couldn't load the analysis</h2>
          <p className="fa-muted">{error}</p>
          <div className="fa-actions">
            <button className="fa-btn fa-btn-primary" onClick={analyze}>
              Try Again
            </button>
            <button className="fa-btn" onClick={handleUseDifferentDataset}>
              Use a different dataset
            </button>
            <button className="fa-btn" onClick={() => navigate("/start")}>
              Back
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ---------------------------------------------------------
  // Report (stage === READY)
  // ---------------------------------------------------------

  const health = report?.health || { total_issues: 0, by_category: {}, issues: [] };
  const forecast = report?.forecast || {};
  const plan = report?.plan || {};
  const decisions = report?.human_decisions || [];
  const nextActions = report?.next_best_actions || [];
  const readiness = report?.readiness || {};

  const counts = { ...health.by_category };
  const orderedCategories = Object.keys(counts).sort((a, b) => {
    const orderA = CATEGORY_INFO[a]?.order ?? 99;
    const orderB = CATEGORY_INFO[b]?.order ?? 99;
    return orderA - orderB;
  });

  const criticalCount = (health.issues || []).filter(
    (i) => i.severity === "CRITICAL",
  ).length;

  const planTone =
    plan.status === "OPTIMAL" || plan.status === "FEASIBLE"
      ? "good"
      : plan.status === "NEEDS_HUMAN_INPUT"
        ? "warn"
        : "bad";

  const isHealthy = health.total_issues === 0;

  // A single plain-English sentence up top so someone can understand the
  // state of the backlog without reading the whole page.
  const headline = isHealthy
    ? "This backlog looks healthy — no issues were found."
    : criticalCount > 0
      ? `${criticalCount} critical issue${criticalCount === 1 ? "" : "s"} ${
          criticalCount === 1 ? "needs" : "need"
        } attention before this plan can be trusted.`
      : `${health.total_issues} issue${health.total_issues === 1 ? "" : "s"} found — none critical, but worth reviewing.`;

  return (
    <div className="fa-page">
      <div className="fa-shell">
        <header className="fa-header">
          <div>
            <div className="fa-eyebrow">FOREMAN ANALYSIS</div>
            <h1>How healthy is this backlog?</h1>
            <p className="fa-subtitle">
              A plain-English read on readiness, dependencies, capacity, and
              the delivery forecast — generated by the Foreman engine, not by
              an LLM.
            </p>
          </div>

          <div className="fa-header-actions">
            <button className="fa-btn" onClick={analyze}>
              ↻ Re-run
            </button>
            <button className="fa-btn" onClick={() => navigate("/start")}>
              Back
            </button>
          </div>
        </header>

        <div className="fa-dataset-chip">
          <span className="fa-dataset-dot" />
          Dataset: <strong>{datasetSource || "Unknown"}</strong>
          <button
            type="button"
            className="fa-link-btn fa-dataset-swap"
            onClick={handleUseDifferentDataset}
          >
            Use a different dataset
          </button>
        </div>

        {/* ------------------------------------------------- */}
        {/* Headline — one sentence anyone can understand      */}
        {/* ------------------------------------------------- */}

        <section
          className={`fa-headline fa-headline-${
            isHealthy ? "good" : criticalCount > 0 ? "bad" : "warn"
          }`}
        >
          <span className="fa-headline-icon">
            {isHealthy ? "✅" : criticalCount > 0 ? "🚫" : "⚠️"}
          </span>
          <p>{headline}</p>
        </section>

        {/* ------------------------------------------------- */}
        {/* Top-line summary — the 4 numbers that matter most  */}
        {/* ------------------------------------------------- */}

        <section className="fa-summary-row">
          <div className="fa-summary-tile">
            <div className="fa-summary-value">{health.total_issues}</div>
            <div className="fa-summary-label">Issues found</div>
          </div>

          <div className="fa-summary-tile">
            <div className="fa-summary-value">
              {forecast.projected_completion_sprint || "Unknown"}
            </div>
            <div className="fa-summary-label">Projected completion</div>
          </div>

          <div className="fa-summary-tile">
            <div className="fa-summary-value">{pct(forecast.confidence)}</div>
            <div className="fa-summary-label">Forecast confidence</div>
          </div>

          <div className="fa-summary-tile">
            <Pill tone={planTone}>{plan.status || "UNKNOWN"}</Pill>
            <div className="fa-summary-label">Sprint plan status</div>
          </div>
        </section>

        <div className="fa-grid">
          {/* ----------------------------------------------- */}
          {/* Issues by category                               */}
          {/* ----------------------------------------------- */}

          <section className="fa-card">
            <div className="fa-card-title">Issues by category</div>

            {orderedCategories.length === 0 ? (
              <p className="fa-muted">No issues found — this backlog looks healthy.</p>
            ) : (
              <ul className="fa-bar-list">
                {orderedCategories.map((category) => {
                  const max = Math.max(...Object.values(counts), 1);
                  const width = Math.max((counts[category] / max) * 100, 6);
                  return (
                    <li key={category} className="fa-bar-item">
                      <div className="fa-bar-row">
                        <span className="fa-bar-label">{category}</span>
                        <div className="fa-bar-track">
                          <div className="fa-bar-fill" style={{ width: `${width}%` }} />
                        </div>
                        <span className="fa-bar-count">{counts[category]}</span>
                      </div>
                      {CATEGORY_INFO[category]?.blurb && (
                        <p className="fa-bar-blurb">{CATEGORY_INFO[category].blurb}</p>
                      )}
                    </li>
                  );
                })}
              </ul>
            )}

            {health.issues?.length > 0 && (
              <button
                type="button"
                className="fa-link-btn"
                onClick={() => setOpenPanel(openPanel === "issues" ? null : "issues")}
              >
                {openPanel === "issues" ? "Hide the full list" : "See every issue"}
              </button>
            )}
          </section>

          {/* ----------------------------------------------- */}
          {/* Forecast, explained                              */}
          {/* ----------------------------------------------- */}

          <section className="fa-card">
            <div className="fa-card-title">Delivery forecast</div>

            <p className="fa-explainer">
              At the current pace ({forecast.median_velocity ?? "—"} points/sprint,
              based on {forecast.historical_sprints ?? 0} completed sprint
              {forecast.historical_sprints === 1 ? "" : "s"}), the remaining{" "}
              <strong>{forecast.remaining_points ?? "—"}</strong> points are
              projected to finish around{" "}
              <strong>{forecast.projected_completion_sprint || "an unknown sprint"}</strong>.
            </p>

            {Array.isArray(forecast.assumptions) && forecast.assumptions.length > 0 && (
              <>
                <div className="fa-subhead">This assumes:</div>
                <ul className="fa-assumptions">
                  {forecast.assumptions.map((a, i) => (
                    <li key={i}>{a}</li>
                  ))}
                </ul>
              </>
            )}
          </section>

          {/* ----------------------------------------------- */}
          {/* Readiness + plan                                 */}
          {/* ----------------------------------------------- */}

          <section className="fa-card">
            <div className="fa-card-title">Readiness &amp; sprint plan</div>

            <div className="fa-kv-row">
              <span className="fa-muted">Ready items</span>
              <strong>{readiness.ready_items ?? "—"}</strong>
            </div>
            <div className="fa-kv-row">
              <span className="fa-muted">Blocked (not Ready)</span>
              <strong>{readiness.blocked_items ?? "—"}</strong>
            </div>
            <div className="fa-kv-row">
              <span className="fa-muted">Scheduled this run</span>
              <strong>{Array.isArray(plan.items) ? plan.items.length : 0}</strong>
            </div>

            {plan.commitment_status === "NOT_EXECUTABLE" && (
              <div className="fa-warning-banner">
                Not executable yet — critical dependency issues must be fixed first.
              </div>
            )}

            {Array.isArray(plan.items) && plan.items.length > 0 && (
              <button
                type="button"
                className="fa-link-btn"
                onClick={() => setOpenPanel(openPanel === "plan" ? null : "plan")}
              >
                {openPanel === "plan" ? "Hide scheduled items" : "See scheduled items"}
              </button>
            )}
          </section>
        </div>

        {/* ----------------------------------------------- */}
        {/* Decisions a human needs to make                  */}
        {/* ----------------------------------------------- */}

        {decisions.length > 0 && (
          <section className="fa-card">
            <div className="fa-card-title">Decisions that need a human</div>
            <p className="fa-muted" style={{ marginTop: -8, marginBottom: 14 }}>
              Foreman won't act on these automatically — it's flagging them for
              you to decide.
            </p>

            <div className="fa-decisions">
              {decisions.map((decision) => (
                <div key={decision.decision_id} className="fa-decision">
                  <span className="fa-decision-category">{decision.category}</span>
                  <p className="fa-decision-question">{decision.question}</p>
                  <p className="fa-muted">{decision.recommendation}</p>
                  {Array.isArray(decision.evidence) && decision.evidence.length > 0 && (
                    <ul className="fa-assumptions">
                      {decision.evidence.map((line, i) => (
                        <li key={i}>{line}</li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}
            </div>
          </section>
        )}

        {nextActions.length > 0 && (
          <section className="fa-card">
            <div className="fa-card-title">Suggested next steps</div>
            <ol className="fa-next-actions">
              {nextActions.map((action, i) => (
                <li key={i}>{action}</li>
              ))}
            </ol>
          </section>
        )}

        {/* ----------------------------------------------- */}
        {/* Detail panels                                    */}
        {/* ----------------------------------------------- */}

        {openPanel === "issues" && (
          <section className="fa-card fa-detail">
            <div className="fa-card-title">All issues</div>
            <div className="fa-table-wrap">
              <table className="fa-table">
                <thead>
                  <tr>
                    <th>Severity</th>
                    <th>Category</th>
                    <th>Ticket / Sprint</th>
                    <th>Message</th>
                  </tr>
                </thead>
                <tbody>
                  {(health.issues || []).map((issue, i) => (
                    <tr key={i}>
                      <td>
                        <Pill
                          tone={
                            issue.severity === "CRITICAL"
                              ? "bad"
                              : issue.severity === "HIGH"
                                ? "warn"
                                : "neutral"
                          }
                        >
                          {issue.severity}
                        </Pill>
                      </td>
                      <td>{issue.category}</td>
                      <td>{issue.ticket_id || issue.sprint_id || "—"}</td>
                      <td>{issue.message}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        )}

        {openPanel === "plan" && (
          <section className="fa-card fa-detail">
            <div className="fa-card-title">Scheduled items</div>
            <div className="fa-table-wrap">
              <table className="fa-table">
                <thead>
                  <tr>
                    <th>Ticket</th>
                    <th>Title</th>
                    <th>Sprint</th>
                    <th>Points</th>
                    <th>Priority</th>
                  </tr>
                </thead>
                <tbody>
                  {(plan.items || []).map((item) => (
                    <tr key={item.ticket_id}>
                      <td>{item.ticket_id}</td>
                      <td>{item.title}</td>
                      <td>{item.sprint_name || item.sprint_id}</td>
                      <td>{item.story_points}</td>
                      <td>{item.priority}</td>
                    </tr>
                  ))}
                  {(!plan.items || plan.items.length === 0) && (
                    <tr>
                      <td colSpan={5} className="fa-muted">
                        Nothing scheduled{plan.message ? ` — ${plan.message}` : "."}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>
        )}
      </div>
    </div>
  );
}
