import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

import { loadForemanDataset, runForemanAnalysis } from "../services/foremanAnalysisApi";
import "./ForemanAnalysis.css";

// Friendlier labels + order for the issue categories the backend returns.
const CATEGORY_ORDER = [
  "Capacity",
  "Dependency",
  "Readiness",
  "Hierarchy",
  "Traceability",
  "Estimation",
];

function pct(confidence) {
  if (confidence == null) return "—";
  return `${Math.round(confidence * 100)}%`;
}

function Pill({ tone, children }) {
  return <span className={`fa-pill fa-pill-${tone}`}>{children}</span>;
}

export default function ForemanAnalysis() {
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const [report, setReport] = useState(null);
  const [openPanel, setOpenPanel] = useState(null); // "issues" | "plan"

  const load = useCallback(async ({ isRefresh = false } = {}) => {
    isRefresh ? setRefreshing(true) : setLoading(true);
    setError("");

    try {
      await loadForemanDataset();
      const result = await runForemanAnalysis();
      setReport(result);
    } catch (err) {
      console.error("Foreman analysis failed:", err);
      setError(
        err.message ||
          "Could not reach the backend. Is it running on http://localhost:8000?",
      );
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  if (loading) {
    return (
      <div className="fa-page">
        <div className="fa-card fa-center">
          <div className="fa-spinner" />
          <p>Running Foreman analysis…</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="fa-page">
        <div className="fa-card fa-center">
          <div className="fa-error-icon">⚠️</div>
          <h2>Couldn't load the analysis</h2>
          <p className="fa-muted">{error}</p>
          <div className="fa-actions">
            <button className="fa-btn fa-btn-primary" onClick={() => load()}>
              Try Again
            </button>
            <button className="fa-btn" onClick={() => navigate("/start")}>
              Back
            </button>
          </div>
        </div>
      </div>
    );
  }

  const health = report?.health || { total_issues: 0, by_category: {}, issues: [] };
  const forecast = report?.forecast || {};
  const plan = report?.plan || {};
  const decisions = report?.human_decisions || [];
  const nextActions = report?.next_best_actions || [];
  const readiness = report?.readiness || {};

  const counts = { ...health.by_category };
  const orderedCategories = [
    ...CATEGORY_ORDER.filter((c) => c in counts),
    ...Object.keys(counts).filter((c) => !CATEGORY_ORDER.includes(c)),
  ];

  const planTone =
    plan.status === "OPTIMAL" || plan.status === "FEASIBLE"
      ? "good"
      : plan.status === "NEEDS_HUMAN_INPUT"
        ? "warn"
        : "bad";

  return (
    <div className="fa-page">
      <div className="fa-shell">
        <header className="fa-header">
          <div>
            <div className="fa-eyebrow">FOREMAN ANALYSIS</div>
            <h1>How healthy is this backlog?</h1>
            <p className="fa-subtitle">
              A plain-English read on readiness, dependencies, capacity, and
              the delivery forecast — generated by the Foreman engine, not by
              the LLM.
            </p>
          </div>

          <div className="fa-header-actions">
            <button className="fa-btn" onClick={() => load({ isRefresh: true })} disabled={refreshing}>
              {refreshing ? "Refreshing…" : "↻ Refresh"}
            </button>
            <button className="fa-btn" onClick={() => navigate("/start")}>
              Back
            </button>
          </div>
        </header>

        {/* ------------------------------------------------- */}
        {/* Top-line summary — the 3 numbers that matter most  */}
        {/* ------------------------------------------------- */}

        <section className="fa-summary-row">
          <div className="fa-summary-tile">
            <div className="fa-summary-value">{health.total_issues}</div>
            <div className="fa-summary-label">Issues found</div>
          </div>

          <div className="fa-summary-tile">
            <div className="fa-summary-value">
              {forecast.projected_completion_sprint || "Unknown"}
            </div>
            <div className="fa-summary-label">Projected completion</div>
          </div>

          <div className="fa-summary-tile">
            <div className="fa-summary-value">{pct(forecast.confidence)}</div>
            <div className="fa-summary-label">Forecast confidence</div>
          </div>

          <div className="fa-summary-tile">
            <Pill tone={planTone}>{plan.status || "UNKNOWN"}</Pill>
            <div className="fa-summary-label">Sprint plan status</div>
          </div>
        </section>

        <div className="fa-grid">
          {/* ----------------------------------------------- */}
          {/* Issues by category                               */}
          {/* ----------------------------------------------- */}

          <section className="fa-card">
            <div className="fa-card-title">Issues by category</div>

            {orderedCategories.length === 0 ? (
              <p className="fa-muted">No issues found — this backlog looks healthy.</p>
            ) : (
              <ul className="fa-bar-list">
                {orderedCategories.map((category) => {
                  const max = Math.max(...Object.values(counts), 1);
                  const width = Math.max((counts[category] / max) * 100, 6);
                  return (
                    <li key={category} className="fa-bar-row">
                      <span className="fa-bar-label">{category}</span>
                      <div className="fa-bar-track">
                        <div className="fa-bar-fill" style={{ width: `${width}%` }} />
                      </div>
                      <span className="fa-bar-count">{counts[category]}</span>
                    </li>
                  );
                })}
              </ul>
            )}

            <button
              type="button"
              className="fa-link-btn"
              onClick={() => setOpenPanel(openPanel === "issues" ? null : "issues")}
            >
              {openPanel === "issues" ? "Hide the full list" : "See every issue"}
            </button>
          </section>

          {/* ----------------------------------------------- */}
          {/* Forecast, explained                              */}
          {/* ----------------------------------------------- */}

          <section className="fa-card">
            <div className="fa-card-title">Delivery forecast</div>

            <p className="fa-explainer">
              At the current pace ({forecast.median_velocity ?? "—"} points/sprint,
              based on {forecast.historical_sprints ?? 0} completed sprint
              {forecast.historical_sprints === 1 ? "" : "s"}), the remaining{" "}
              <strong>{forecast.remaining_points ?? "—"}</strong> points are
              projected to finish around{" "}
              <strong>{forecast.projected_completion_sprint || "an unknown sprint"}</strong>.
            </p>

            {Array.isArray(forecast.assumptions) && forecast.assumptions.length > 0 && (
              <>
                <div className="fa-subhead">This assumes:</div>
                <ul className="fa-assumptions">
                  {forecast.assumptions.map((a, i) => (
                    <li key={i}>{a}</li>
                  ))}
                </ul>
              </>
            )}
          </section>

          {/* ----------------------------------------------- */}
          {/* Readiness + plan                                 */}
          {/* ----------------------------------------------- */}

          <section className="fa-card">
            <div className="fa-card-title">Readiness &amp; sprint plan</div>

            <div className="fa-kv-row">
              <span className="fa-muted">Ready items</span>
              <strong>{readiness.ready_items ?? "—"}</strong>
            </div>
            <div className="fa-kv-row">
              <span className="fa-muted">Blocked (not Ready)</span>
              <strong>{readiness.blocked_items ?? "—"}</strong>
            </div>
            <div className="fa-kv-row">
              <span className="fa-muted">Scheduled this run</span>
              <strong>{Array.isArray(plan.items) ? plan.items.length : 0}</strong>
            </div>

            {plan.commitment_status === "NOT_EXECUTABLE" && (
              <div className="fa-warning-banner">
                Not executable yet — critical dependency issues must be fixed first.
              </div>
            )}

            <button
              type="button"
              className="fa-link-btn"
              onClick={() => setOpenPanel(openPanel === "plan" ? null : "plan")}
            >
              {openPanel === "plan" ? "Hide scheduled items" : "See scheduled items"}
            </button>
          </section>
        </div>

        {/* ----------------------------------------------- */}
        {/* Decisions a human needs to make                  */}
        {/* ----------------------------------------------- */}

        {decisions.length > 0 && (
          <section className="fa-card">
            <div className="fa-card-title">Decisions that need a human</div>
            <p className="fa-muted" style={{ marginTop: -8, marginBottom: 14 }}>
              Foreman won't act on these automatically — it's flagging them for
              you to decide.
            </p>

            <div className="fa-decisions">
              {decisions.map((decision) => (
                <div key={decision.decision_id} className="fa-decision">
                  <span className="fa-decision-category">{decision.category}</span>
                  <p className="fa-decision-question">{decision.question}</p>
                  <p className="fa-muted">{decision.recommendation}</p>
                  {Array.isArray(decision.evidence) && decision.evidence.length > 0 && (
                    <ul className="fa-assumptions">
                      {decision.evidence.map((line, i) => (
                        <li key={i}>{line}</li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}
            </div>
          </section>
        )}

        {nextActions.length > 0 && (
          <section className="fa-card">
            <div className="fa-card-title">Suggested next steps</div>
            <ol className="fa-next-actions">
              {nextActions.map((action, i) => (
                <li key={i}>{action}</li>
              ))}
            </ol>
          </section>
        )}

        {/* ----------------------------------------------- */}
        {/* Detail panels                                    */}
        {/* ----------------------------------------------- */}

        {openPanel === "issues" && (
          <section className="fa-card fa-detail">
            <div className="fa-card-title">All issues</div>
            <div className="fa-table-wrap">
              <table className="fa-table">
                <thead>
                  <tr>
                    <th>Severity</th>
                    <th>Category</th>
                    <th>Ticket / Sprint</th>
                    <th>Message</th>
                  </tr>
                </thead>
                <tbody>
                  {(health.issues || []).map((issue, i) => (
                    <tr key={i}>
                      <td>
                        <Pill
                          tone={
                            issue.severity === "CRITICAL"
                              ? "bad"
                              : issue.severity === "HIGH"
                                ? "warn"
                                : "neutral"
                          }
                        >
                          {issue.severity}
                        </Pill>
                      </td>
                      <td>{issue.category}</td>
                      <td>{issue.ticket_id || issue.sprint_id || "—"}</td>
                      <td>{issue.message}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        )}

        {openPanel === "plan" && (
          <section className="fa-card fa-detail">
            <div className="fa-card-title">Scheduled items</div>
            <div className="fa-table-wrap">
              <table className="fa-table">
                <thead>
                  <tr>
                    <th>Ticket</th>
                    <th>Title</th>
                    <th>Sprint</th>
                    <th>Points</th>
                    <th>Priority</th>
                  </tr>
                </thead>
                <tbody>
                  {(plan.items || []).map((item) => (
                    <tr key={item.ticket_id}>
                      <td>{item.ticket_id}</td>
                      <td>{item.title}</td>
                      <td>{item.sprint_name || item.sprint_id}</td>
                      <td>{item.story_points}</td>
                      <td>{item.priority}</td>
                    </tr>
                  ))}
                  {(!plan.items || plan.items.length === 0) && (
                    <tr>
                      <td colSpan={5} className="fa-muted">
                        Nothing scheduled{plan.message ? ` — ${plan.message}` : "."}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </section>
        )}
      </div>
    </div>
  );
}
